services:
  - type: web
    name: mtn-groupshare
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MTN_PHONE
        sync: false
      - key: MTN_PIN
        sync: false
      - key: OTP_PORT
        value: 6060
      - key: API_PORT
        value: 7070
      - key: NGROK_AUTHTOKEN
        sync: false
      - key: NGROK_DOMAIN
        sync: false
      - key: EXCEL_FOLDER_PATH
        value: /data/upload_files
    healthCheckPath: /health
    disk:
      name: groupshare-data
      mountPath: /data/upload_files
      sizeGB: 1